name: Expresiones
run-name: ¡Aprendiendo Expresiones con GitHub Actions!

on:
  workflow_dispatch:
    inputs:
      edad:
        description: "Edad"
        required: true
        type: integer
      nombre:
        description: "Nombre"
        required: true
        default: "Jose"
        type: string

jobs:
  mayor:
    if: ${{ edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad

  menor:
    if: ${{ edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es menor de edad
